"""Build the live data DB from real Manifold data (Phase LD orchestrator).

Steps:
  1. Backfill curated open markets: real prices + features (Task LD.3).
  2. Train the calibration model on a real resolved-market corpus and store honest predictions for
     every open market (Task LD.5), reporting Brier score vs. the market baseline.

Later tasks (LD.6–LD.7) add the signal detectors. Produces a DB the API can serve directly.

Usage:
    uv run python scripts/build_live_db.py --db ../data/parallax-live.db
    uv run python scripts/build_live_db.py --db ../data/parallax-live.db --skip-model
"""

from __future__ import annotations

import argparse
import sqlite3
from pathlib import Path

import httpx
import numpy as np

from parallax_research.calibration.dataset import extract_training_dataset
from parallax_research.calibration.edge import evaluate_and_store
from parallax_research.calibration.model import BaselineModel
from parallax_research.calibration.scoring import (
    brier_score,
    expected_calibration_error,
)
from parallax_research.ingest.backfill import backfill_registry
from parallax_research.ingest.training import backfill_training_corpus

_REPO_ROOT = Path(__file__).resolve().parents[2]


def _log_loss(y_true, y_prob) -> float:
    y = np.asarray(y_true, dtype=float)
    p = np.clip(np.asarray(y_prob, dtype=float), 1e-6, 1 - 1e-6)
    return float(-np.mean(y * np.log(p) + (1 - y) * np.log(1 - p)))


def _write_report(n_markets: int, n_rows: int, m: dict[str, float]) -> None:
    """Write the honest live-calibration report the Performance page renders."""
    better = "model" if m["brier_model"] < m["brier_market"] else "market price"
    verdict = (
        "the **market price is better calibrated than our model**"
        if better == "market price"
        else "our model edges out the market price"
    )
    report = f"""# Live calibration — model vs. Manifold market

_Auto-generated by `scripts/build_live_db.py` from real resolved Manifold markets — reproducible,
not hand-written._

A logistic-regression calibration baseline (features: probability velocity, bet-arrival rate,
realized volatility, market price) trained on **{n_markets} resolved markets** ({n_rows} labeled
feature snapshots), scored on a held-out 20% against the market's own implied price.

| Metric (holdout, lower is better) | Model | Market price |
| --- | --- | --- |
| Brier score | {m["brier_model"]:.4f} | {m["brier_market"]:.4f} |
| Log loss | {m["logloss_model"]:.4f} | {m["logloss_market"]:.4f} |
| Expected calibration error | {m["ece_model"]:.4f} | {m["ece_market"]:.4f} |

**Verdict:** {verdict} (Brier {m["brier_model"]:.4f} vs {m["brier_market"]:.4f}).

We report this transparently. A simple model over four features does **not** reliably beat a liquid
market's own price, and pretending otherwise would be the dishonest move. The per-market *edge* shown
on the Markets page is the model's **disagreement** with the price — useful for spotting where the
model and market diverge, not a profit guarantee.
"""
    out = _REPO_ROOT / "reports" / "calibration-live.md"
    out.write_text(report)
    print(f"  wrote {out.relative_to(_REPO_ROOT)}")


def _fit_and_store(live_conn: sqlite3.Connection, *, client: httpx.Client, max_markets: int) -> None:
    print("Building resolved-market training corpus (this fetches bet history) …")
    corpus = sqlite3.connect(":memory:")
    try:
        rows = backfill_training_corpus(corpus, client=client, max_markets=max_markets)
        df = extract_training_dataset(corpus)
    finally:
        corpus.close()
    print(f"  training rows={len(df)} (from {rows} feature snapshots)")

    enough = len(df) >= 30 and df["outcome"].nunique() >= 2
    if not enough:
        print("  ! corpus too small / single-class — model falls back to base rate.")

    # Honest skill check: hold out 20%, compare the model's calibration to the market-price baseline.
    holdout = df.sample(frac=0.2, random_state=0) if enough else df
    train = df.drop(holdout.index) if enough else df
    model = BaselineModel().fit(train)
    if enough and len(holdout):
        y = holdout["outcome"]
        pm = model.predict_proba(holdout)
        pk = holdout["market_prob"].to_numpy(dtype=float)
        metrics = {
            "brier_model": brier_score(y, pm),
            "brier_market": brier_score(y, pk),
            "logloss_model": _log_loss(y, pm),
            "logloss_market": _log_loss(y, pk),
            "ece_model": expected_calibration_error(y, pm),
            "ece_market": expected_calibration_error(y, pk),
        }
        verdict = "model better" if metrics["brier_model"] < metrics["brier_market"] else "market better"
        print(
            f"  Brier  model={metrics['brier_model']:.4f}  market={metrics['brier_market']:.4f}"
            f"  → {verdict} (lower is better)"
        )
        n_markets = int(df["market_id"].nunique())
        _write_report(n_markets, len(df), metrics)

    # Refit on all data for production predictions; store every open market (min_ev < 0 keeps the
    # negative-edge ones too, so the dashboard shows the model's view on every market, not just bets).
    model_full = BaselineModel().fit(df)
    stored = evaluate_and_store(live_conn, model_full, fee=0.0, slippage=0.0, min_ev=-1.0)
    print(f"  stored predictions for {stored} open markets")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", default="../data/parallax-live.db", help="SQLite path to build")
    parser.add_argument("--skip-model", action="store_true", help="skip model training/prediction")
    parser.add_argument("--train-markets", type=int, default=120, help="resolved markets to train on")
    args = parser.parse_args()

    conn = sqlite3.connect(args.db)
    client = httpx.Client(timeout=20.0)
    try:
        print(f"Backfilling curated Manifold markets into {args.db} …")
        counts = backfill_registry(conn, client=client)
        print(
            f"  markets={counts.markets}  bets={counts.bets}  "
            f"snapshots={counts.snapshots}  features={counts.features}"
        )
        if not args.skip_model:
            _fit_and_store(conn, client=client, max_markets=args.train_markets)
    finally:
        client.close()
        conn.close()
    print("Done.")


if __name__ == "__main__":
    main()
